### PR TITLE
Nyan kiyoshi patch 1

### PR DESCRIPTION
**Pull request by NyanKiyoshi**

### CODE REVIEW

**Comment by django-queries** [comment]
blah

**Comment by NyanKiyoshi** [comment]
Missing head report (0041bb10c3db7c5c97664bf62f5735cd5cb1afe2). The results couldn't be compared.

```diff
# fixture is invoked when marked
  test name                 	left count 	right count
  --------------------------	-----------	-----------
  count db query number     	          3	          3

# plugin exports results even when test fails
  test name                 	left count 	right count
  --------------------------	-----------	-----------
  failure                   	          1	          1
  wfailure                  	          1	          1
  wwfailure                 	          1	          1
```

**Comment by NyanKiyoshi** [comment]
Missing head report (0041bb10c3db7c5c97664bf62f5735cd5cb1afe2). The results couldn't be compared.

```diff
# fixture is invoked when marked
  test name                 	left count 	right count
  --------------------------	-----------	-----------
  count db query number     	          3	          3

# plugin exports results even when test fails
  test name                 	left count 	right count
  --------------------------	-----------	-----------
  failure                   	          1	          1
  wfailure                  	          1	          1
  wwfailure                 	          1	          1
```

**Comment by NyanKiyoshi** [comment]
Missing head report (0041bb10c3db7c5c97664bf62f5735cd5cb1afe2). The results couldn't be compared.

```diff
# fixture is invoked when marked
  test name                 	left count 	right count
  --------------------------	-----------	-----------
  count db query number     	          3	          3

# plugin exports results even when test fails
  test name                 	left count 	right count
  --------------------------	-----------	-----------
  failure                   	          1	          1
  wfailure                  	          1	          1
  wwfailure                 	          1	          1
```

**Comment by NyanKiyoshi** [comment]
Missing head report (0041bb10c3db7c5c97664bf62f5735cd5cb1afe2). The results couldn't be compared.

```diff
# fixture is invoked when marked
  test name                 	left count 	right count
  --------------------------	-----------	-----------
  count db query number     	          3	          3

# plugin exports results even when test fails
  test name                 	left count 	right count
  --------------------------	-----------	-----------
  failure                   	          1	          1
  wfailure                  	          1	          1
  wwfailure                 	          1	          1
```

**Comment by NyanKiyoshi** [comment]
Missing head report (0041bb10c3db7c5c97664bf62f5735cd5cb1afe2). The results couldn't be compared.

Here is the report for 3d06b2ebc6b610b1c7ba082f601d2bba23672538 (NyanKiyoshi/testing @ master)

```diff
# fixture is invoked when marked
  test name                 	left count 	right count
  --------------------------	-----------	-----------
  count db query number     	          3	          3

# plugin exports results even when test fails
  test name                 	left count 	right count
  --------------------------	-----------	-----------
  failure                   	          1	          1
  wfailure                  	          0	          0
  wwfailure                 	          3	          3
```

**Pull request merged**
